export let cars = [
    {
        id: 1,
        name: 'Mercedes-Benz G63',
        price: 300000,
        image: 'https://www.hdcarwallpapers.com/download/2019_brabus_800_widestar_mercedes_amg_g63_4k_2-2560x1440.jpg',
        MainDescription: 'G63. Without words.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
    {
        id: 2,
        name: 'BMW M3',
        price: 210000,
        image: 'https://www.hdcarwallpapers.com/download/bmw_m3_competition_2021_5k_2-2560x1440.jpg',
        MainDescription: 'BMW M3. Style. Street. Speed.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
    {
        id: 3,
        name: 'Lamborghini Huracán Performante Spyder',
        price: 400000,
        image: 'https://www.hdcarwallpapers.com/download/lamborghini_huracan_performante_spyder_4k-2560x1440.jpg',
        MainDescription: 'Lamborghini. Faster than the others.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
    {
        id: 4,
        name: 'McLaren 765LT',
        price: 430000,
        image: 'https://www.hdcarwallpapers.com/download/topcar_mclaren_765lt_carbon_body_twill_4x4_2022_5k_2-2560x1440.jpg',
        MainDescription: 'McLaren. Acceleration. Power. Controllability.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
]
export const defaultCars = [
    {
        id: 1,
        name: 'Mercedes-Benz G63',
        price: 300000,
        image: 'https://www.hdcarwallpapers.com/download/2019_brabus_800_widestar_mercedes_amg_g63_4k_2-2560x1440.jpg',
        MainDescription: 'G63. Without words.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
    {
        id: 2,
        name: 'BMW M3',
        price: 210000,
        image: 'https://www.hdcarwallpapers.com/download/bmw_m3_competition_2021_5k_2-2560x1440.jpg',
        MainDescription: 'BMW M3. Style. Street. Speed.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
    {
        id: 3,
        name: 'Lamborghini Huracán Performante Spyder',
        price: 400000,
        image: 'https://www.hdcarwallpapers.com/download/lamborghini_huracan_performante_spyder_4k-2560x1440.jpg',
        MainDescription: 'Lamborghini. Faster than the others.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
    {
        id: 4,
        name: 'McLaren 765LT',
        price: 430000,
        image: 'https://www.hdcarwallpapers.com/download/topcar_mclaren_765lt_carbon_body_twill_4x4_2022_5k_2-2560x1440.jpg',
        MainDescription: 'McLaren. Acceleration. Power. Controllability.',
        imageEngine: '',
        descriptionEngine: 'eng',
        imageInterior: '',
        descriptionInterior: 'inter',
        imageExterior: '',
        descriptionExterior: 'exter',
    },
]